config/routes.rb
Rails.application.routes.draw do

  #resources :vouchers
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/ecommerce'
  mount Crono::Web, at: '/crono'

  get 'ecommerce/order/paid/:id' => 'spree/checkout#paid'

  root 'dashboard#index'

  #get 'user_sessions/new'
  #get 'user_sessions/create'
  #get 'user_sessions/destroy'
  #root :to => 'users#index'
  resources :user_sessions
  resources :users
  #resources :factory_manual_managment

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  post 'sort_wh' => 'managments#sort_wh', as: :sort_warehouses
  post 'enviar_factura' => 'managments#enviar_factura', as: :enviar_factura
  post 'activate_queue' => 'general#activate_queue', as: :activate_queue
  post 'notify_deliver' => 'managments#notify_deliver', as: :notify_deliver
  post 'pay_invoice' => 'managments#pay_invoice', as: :pay_invoice
  post 'deliver' => 'managments#deliver', as: :deliver
  post 'deliver_ftp' => 'managments#deliver_ftp', as: :deliver_ftp
  post 'create_oc' => 'managments#create_oc', as: :create_oc
  post 'accept_oc' => 'general#accept_oc', as: :accept_oc
  post 'accept_invoice' => 'general#accept_invoice', as: :accept_invoice
  post 'encolar_order' => 'managments#encolar_order', as: :encolar_order
  post 'desencolar_order' => 'managments#desencolar_order', as: :desencolar_order
  post 'accept_ftp' => 'general#accept_ftp', as: :accept_ftp
  post 'detener_despacho' => 'managments#detener_despacho', as: :detener_despacho
  post 'despachar_boleta' => 'managments#despachar_boleta', as: :despachar_boleta
  post 'sent_production' => 'managments#sent_production', as: :sent_production
  post 'mover_cantidad' => 'managments#mover_cantidad', as: :mover_cantidad
  post 'check_for_availablility' => 'managments#check_for_availablility', as: :check_for_availablility
  post 'asociar_factura_transaccion' => 'general#asociar_factura_transaccion', as: :asociar_factura_transaccion


  post 'refresh_transactions' => 'managments#refresh_transactions', as: :refresh_transactions
  post 'refresh_ftp' => 'managments#refresh_ftp', as: :refresh_ftp
  get 'refresh_ftp' => 'managments#refresh_ftp'

  post 'refresh_balance' => 'managments#refresh_balance', as: :refresh_balance

  post 'refresh_purchase_orders' => 'managments#refresh_purchase_orders', as: :refresh_purchase_orders
  post 'refresh_invoices' => 'managments#refresh_invoices', as: :refresh_invoices
  post 'stocks_force_update' => 'managments#stocks_force_update', as: :stocks_force_update

  post 'move_despacho_general' => 'managments#move_despacho_general', as: :move_despacho_general
  post 'move_recepcion_general' => 'managments#move_recepcion_general', as: :move_recepcion_general
  post 'stop_warehouses_reorder' => 'managments#stop_warehouses_reorder', as: :stop_warehouses_reorder


  get 'dashboard/index'

  post 'create_oc_with_price' => 'managments#create_oc_with_price', as: :create_oc_with_price

  #resources :warehouses
  #resources :invoices
  #resources :purchase_orders
  #resources :contacts
  #resources :recipes
  #resources :products
  #resources :suppliers
  apipie
  get 'ftp' => 'api#ftp'
  get 'ofertas' => 'api#get_ofertas'
  get 'update_prices' => 'api#update_prices'
  #get 'test' => 'api#test'
  #get 'test2' => 'api#test2'
  #get 'testj3' => 'api#testj3'
  get 'testj4' => 'api#testj4'
  #get 'tiempo' => 'api#tiempo'


  get 'products' => 'products#available'
  get 'api/publico/precios' => 'products#public_prices'

  get 'general' => 'general#index', :as => :general
  get 'oc' => 'general#oc', :as => :oc
  get 'ventas' => 'general#ventas', :as => :ventas
  get 'ftp_oc' => 'general#ftp_oc', :as => :ftp_oc
  get 'transaction' => 'general#transaction', :as => :transaction
  get 'invoices' => 'general#invoices', :as => :invoices
  get 'production' => 'general#production', :as => :production
  get 'vouchers' => 'general#vouchers', :as => :vouchers
  get 'despacho' => 'general#despacho', :as => :despacho
  get 'promociones' => 'general#promociones', :as => :promociones
  get 'queue' => 'general#queue', :as => :queue
  get 'sprint_5' => 'general#sprint_5', :as => :sprint_5

  get 'invoice_and_transactions' => 'general#invoice_and_transactions', :as => :invoice_and_transactions


  get 'factory_managment' => 'managments#index', :as => :managment


  put 'purchase_orders/:id' => 'purchase_orders#realizar_pedido'

  patch 'purchase_orders/:id/accepted' => 'purchase_orders#confirmar_orden_compra'
  patch 'purchase_orders/:id/rejected' => 'purchase_orders#rechazar_orden_compra'
  #patch 'purchase_orders/:id' => 'purchase_order#responder_orden_compra'

  put 'invoices/:id' => 'invoices#enviar_factura'
  patch 'invoices/:id/accepted' => 'invoices#enviar_confirmacion_factura'
  patch 'invoices/:id/rejected' => 'invoices#enviar_rechazo_factura'
  patch 'invoices/:id/delivered' => 'invoices#notificar_orden_despachada'
  patch 'invoices/:id/paid' => 'invoices#enviar_confirmacion_pago'


  #patch 'suppliers/:id_supplier' => 'suppliers#informar_cuenta_banco'
  get 'buy' => 'products#buy'
  get 'validaciones' => 'api#validacion_local_servidor'
  get 'actualizar_deadlines_purchase_orders' => 'api#actualizar_deadlines_purchase_orders'

  root 'dashboard#index', :as => :dashboard

end

app/models/voucher.rb
class Voucher < ApplicationRecord
	has_many :voucher_stocks

end

app/controllers/vouchers_controller.rb
class VouchersController < ApplicationController
  before_action :set_voucher, only: [:show, :edit, :update, :destroy]

  # GET /vouchers
  def index
    @vouchers = Voucher.all
  end

  # GET /vouchers/1
  def show
  end

  # GET /vouchers/new
  def new
    @voucher = Voucher.new
  end

  # GET /vouchers/1/edit
  def edit
  end

  # POST /vouchers
  def create
    @voucher = Voucher.new(voucher_params)

    if @voucher.save
      redirect_to @voucher, notice: 'Voucher was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /vouchers/1
  def update
    if @voucher.update(voucher_params)
      redirect_to @voucher, notice: 'Voucher was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /vouchers/1
  def destroy
    @voucher.destroy
    redirect_to vouchers_url, notice: 'Voucher was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voucher
      @voucher = Voucher.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def voucher_params
      params.require(:voucher).permit(:id_cloud, :client, :bruto, :iva, :oc_id_cloud, :status)
    end
end

app/helpers/vouchers_helper.rb
module VouchersHelper
end

app/views/vouchers/_form.html.erb
<%= form_for(@voucher) do |f| %>
  <% if @voucher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voucher.errors.count, "error") %> prohibited this voucher from being saved:</h2>

      <ul>
      <% @voucher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_cloud %><br>
    <%= f.text_field :id_cloud %>
  </div>
  <div class="field">
    <%= f.label :client %><br>
    <%= f.text_field :client %>
  </div>
  <div class="field">
    <%= f.label :bruto %><br>
    <%= f.number_field :bruto %>
  </div>
  <div class="field">
    <%= f.label :iva %><br>
    <%= f.number_field :iva %>
  </div>
  <div class="field">
    <%= f.label :oc_id_cloud %><br>
    <%= f.text_field :oc_id_cloud %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vouchers/edit.html.erb
<h1>Editing Voucher</h1>

<%= render 'form' %>

<%= link_to 'Show', @voucher %> |
<%= link_to 'Back', vouchers_path %>

app/views/vouchers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vouchers</h1>

<table>
  <thead>
    <tr>
      <th>Id cloud</th>
      <th>Client</th>
      <th>Bruto</th>
      <th>Iva</th>
      <th>Oc id cloud</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vouchers.each do |voucher| %>
      <tr>
        <td><%= voucher.id_cloud %></td>
        <td><%= voucher.client %></td>
        <td><%= voucher.bruto %></td>
        <td><%= voucher.iva %></td>
        <td><%= voucher.oc_id_cloud %></td>
        <td><%= voucher.status %></td>
        <td><%= link_to 'Show', voucher %></td>
        <td><%= link_to 'Edit', edit_voucher_path(voucher) %></td>
        <td><%= link_to 'Destroy', voucher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voucher', new_voucher_path %>

app/views/vouchers/new.html.erb
<h1>New Voucher</h1>

<%= render 'form' %>

<%= link_to 'Back', vouchers_path %>

app/views/vouchers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id cloud:</strong>
  <%= @voucher.id_cloud %>
</p>

<p>
  <strong>Client:</strong>
  <%= @voucher.client %>
</p>

<p>
  <strong>Bruto:</strong>
  <%= @voucher.bruto %>
</p>

<p>
  <strong>Iva:</strong>
  <%= @voucher.iva %>
</p>

<p>
  <strong>Oc id cloud:</strong>
  <%= @voucher.oc_id_cloud %>
</p>

<p>
  <strong>Status:</strong>
  <%= @voucher.status %>
</p>

<%= link_to 'Edit', edit_voucher_path(@voucher) %> |
<%= link_to 'Back', vouchers_path %>